### ISSUE TITLE
TOC runs off the page for long documents

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs-bootswatch#2]
Originally reported against MkDocs. https://github.com/mkdocs/mkdocs/issues/204

**Comment by memeplex** [comment]
My proposed changed in https://github.com/mkdocs/mkdocs-bootswatch/issues/21 automatically fix this, since they sync bootswatch with the upstream mkdocs theme.

**Comment by adamlwgriffiths** [comment]
This issue still exists in the PyPi released version.
The last version is 0.4.0, released on 2016-03-02, prior to any referenced fixes.

**Comment by jimporter** [comment]
This should be fixed on master, though I'm not totally sure which commit fixed it. Possibly the update to Bootstrap 4?

**Comment by janreggie** [comment]
Oddly, I still have the issue. I'm at bootswatch 1.1 but [this page](https://janreggie.github.io/sicp/1-building-abstractions-using-procedures/)'s TOC runs off to the bottom, and the lowest items can only be seen if the page is scrolled at the very bottom.
I use the Lumen theme but this works for other Bootswatch themes too. Disabling external JavaScript files doesn't seem to help:

```yaml
theme: 
  name: lumen
  navigation_depth: 3
  hljs_languages:
    - scheme
# ...
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.arithmatex:
      generic: true
  - markdown_del_ins:
```

**Comment by jimporter** [comment]
> Oddly, I still have the issue. I'm at bootswatch 1.1 but [this page](https://janreggie.github.io/sicp/1-building-abstractions-using-procedures/)'s TOC runs off to the bottom, and the lowest items can only be seen if the page is scrolled at the very bottom.

That's the "fix"; it's obviously not ideal, but it matches the default `mkdocs` theme (I think). Assuming that's correct, it would probably be best to file an issue on the [mkdocs repo](https://github.com/mkdocs/mkdocs) first, and then port any necessary changes to this one.
